name: ci

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - name: deploy
        run: |
            git config --local user.email "bot-build@plawn.io"
            git config --local user.name "github-actions[bot]"
            bun run deploy
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
